version: '3.7'
services:
  database:
    image: mongo:4.2
    ports:
      - 27018:27018
  development:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/local
    stdin_open: true # docker run -i
    tty: true        # docker run -t
